import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    container: {
        paddingTop: 80,
        paddingLeft: 30,
        paddingRight: 30,
        paddingBottom: 40,
        flex: 1,
        alignItems: "center",
        alignSelf: "stretch",
    },
    container_left: {
        paddingTop: 80,
        paddingLeft: 30,
        paddingRight: 30,
        paddingBottom: 40,
        flex: 1,
        //alignItems: "center",
        alignSelf: "stretch",
    },

    container_scroll: {
        paddingTop: 80,
        paddingLeft: 30,
        paddingRight: 30,
        paddingBottom: 40,
        flex: 1,
        alignSelf: "stretch",
    },
    center: {
        flex: 1,
        justifyContent: 'flex-end',
        alignSelf: "stretch",
    },
    top: {
        flex: 1,
        justifyContent: 'flex-start',
        alignSelf: "stretch",
    },
    middle: {
        position: "relative",
        flexDirection: "row",
        //alignSelf: 'flex-start',
        alignSelf: "stretch",
        paddingLeft: 30,
        paddingRight: 30,
        paddingTop: 30
      },
    inline: {
        flex: 1,
        flexDirection:'row', 
        justifyContent: 'space-between',
        alignSelf: 'stretch',
        paddingTop: 20,
    },
    bottom: {
        flex: 1,
        position: "absolute",
        bottom: 30,
        left: 30,
        right: 30,
        alignSelf: 'stretch',
    },
    keyboard_view: {
        flex: 1,
    },
    header: {
        color: '#2C3B51',
        fontSize: 34,
        lineHeight: 37,
        textAlign: 'center',
        fontFamily: 'roboto-black',
        paddingBottom: 10,
    },
    header_left: {
        color: '#2C3B51',
        fontSize: 34,
        lineHeight: 37,
        textAlign: 'left',
        fontFamily: 'roboto-black',
        paddingBottom: 10,
        alignSelf: 'stretch',
    },
    header_left_padding: {
        color: '#2C3B51',
        fontSize: 34,
        lineHeight: 37,
        textAlign: 'left',
        fontFamily: 'roboto-black',
        paddingBottom: 37,
        alignSelf: 'stretch',
    },
    text: {
        color: '#2C3B51',
        fontSize: 19,
        lineHeight: 25,
        textAlign: 'center',
        fontFamily: 'roboto-regular',
    },
    text_left: {
        //flex: 1,
        color: '#2C3B51',
        fontSize: 19,
        lineHeight: 25,
        textAlign: 'left',
        fontFamily: 'roboto-regular',
        alignSelf: 'stretch',
    },
    text_left_small: {
        flex: 1,
        color: '#2C3B51',
        fontSize: 15,
        lineHeight: 25,
        textAlign: 'left',
        fontFamily: 'roboto-regular',
        alignSelf: 'stretch',
    },
    text_scroll: {
        color: '#2C3B51',
        fontSize: 19,
        lineHeight: 25,
        textAlign: 'left',
        fontFamily: 'roboto-regular',
    },
    codeInput: {
        marginTop: 43,
        alignSelf: "stretch",
        textAlign: 'center',
        height: 40,
        fontSize: 19,
        borderBottomWidth: 2,
    },
    usernameInput: {
        marginTop: 43,
        marginBottom: 43,
        alignSelf: "stretch",
        textAlign: 'center',
        height: 40,
        fontSize: 19,
        borderBottomWidth: 2,
    },
    question: {
        flex:2,
        flexDirection:'row',
        alignSelf: "stretch",
    },
    top_security_agreements: {
        flex: 1,
        justifyContent: 'flex-start',
        alignSelf: "stretch",
        marginTop: -40,
        flexDirection: 'row-reverse',
    },
    close: {
        justifyContent: 'flex-start',
        alignSelf: "stretch",
        paddingTop: 20,
        zIndex: 1,
        left: 20,

    },
    text_bold: {
        color: '#2C3B51',
        fontSize: 19,
        lineHeight: 25,
        fontFamily: 'roboto-bold',
        alignSelf: "stretch",
        textAlign: 'left',
    },
})

export { styles } 